/* Lib kurbo-ffi C++ bindings. */
/* Copyright Daan de Lange 2023-(current-year). */


#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning : this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

enum class KurboPathElType {
  MoveTo,
  LineTo,
  QuadTo,
  CurveTo,
  ClosePath,
};

enum class kurboJoinType {
  Miter,
  Round,
  Bevel,
};

enum class kurboCapType {
  Butt,
  Round,
  Square,
};

struct KurboBezPath;

struct kurboPos {
  double x;
  double y;
};

struct KurboPathEl {
  KurboPathElType tag;
  kurboPos p0;
  kurboPos p1;
  kurboPos p2;
};

using SizeTC = unsigned long;

struct KurboPathRaw {
  const KurboPathEl *data;
  SizeTC len;
};

struct kurboRect {
  double x0;
  double y0;
  double x1;
  double y1;
};

struct kurboEvalResult {
  kurboPos pos;
  kurboPos tangent;
  kurboPos normal;
  double curvature;
};

struct kurboFloatsRaw {
  const double *data;
  SizeTC len;
};

extern "C" {

KurboBezPath *kurbo_path_create(const KurboPathRaw *elements_opt);

void kurbo_path_destroy(KurboBezPath *path);

KurboPathRaw kurbo_path_return_handle_data(KurboBezPath *path);

void kurbo_path_append_move_to(KurboBezPath *path, kurboPos p);

void kurbo_path_append_line_to(KurboBezPath *path, kurboPos p);

void kurbo_path_append_quad_to(KurboBezPath *path, kurboPos p1, kurboPos p2);

void kurbo_path_append_curve_to(KurboBezPath *path, kurboPos p1, kurboPos p2, kurboPos p3);

void kurbo_path_append_close(KurboBezPath *path);

KurboBezPath *kurbo_path_stroke(KurboBezPath *path,
                                double width,
                                kurboJoinType join,
                                double miter_limit,
                                kurboCapType start_cap,
                                kurboCapType end_cap);

void kurbo_path_reverse(KurboBezPath *path);

kurboRect kurbo_path_boundingbox(KurboBezPath *path);

bool kurbo_path_contains_point(KurboBezPath *path, kurboPos pos);

kurboEvalResult kurbo_path_evaluate(KurboBezPath *path, double t);

kurboEvalResult kurbo_path_evaluate_euclidean(KurboBezPath *path, double t, double accuracy);

kurboFloatsRaw kurbo_path_inflections(KurboBezPath *path);

kurboFloatsRaw kurbo_path_extrema(KurboBezPath *path);

KurboBezPath *kurbo_path_offset(KurboBezPath *path, double distance, double tolerance);

void kurbo_path_rotate(KurboBezPath *path, double angle, kurboPos center);

kurboPos kurbo_path_project(KurboBezPath *path, kurboPos pos, double accuracy);

kurboFloatsRaw kurbo_path_self_intersections(KurboBezPath *path,
                                             double error_threshold,
                                             double _min_dist_param);

}  // extern "C"
